.TH "lib/esd/backend Directory Reference" 3 "Sun Feb 3 2019" "Version 0.3" "OpenESS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/esd/backend Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBi2s_gerneric_backend\&.c\fP"
.br
.ti -1c
.RI "file \fBi2s_gerneric_backend\&.h\fP"
.br
.RI "ESS i2s generic backend\&. "
.ti -1c
.RI "file \fBnull_backend\&.c\fP"
.br
.ti -1c
.RI "file \fBnull_backend\&.h\fP"
.br
.RI "ESS null backend - no audio output, only for test\&. "
.ti -1c
.RI "file \fBuart_backend\&.c\fP"
.br
.ti -1c
.RI "file \fBuart_backend\&.h\fP"
.br
.RI "ESS uart backend - write and read audio over UART1\&. "
.ti -1c
.RI "file \fBudp_backend\&.c\fP"
.br
.ti -1c
.RI "file \fBudp_backend\&.h\fP"
.br
.RI "ESS udp backend - send audio over udp4 oder udp6\&. "
.in -1c
