.TH "lib/esd/ess.h" 3 "Sun Feb 3 2019" "Version 0.3" "OpenESS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/esd/ess.h
.SH SYNOPSIS
.br
.PP
\fC#include 'config\&.h'\fP
.br
\fC#include 'ess_format\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBESS_VERSION_1_0\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ESS_VERSION_1_0"

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenESS from the source code\&.
