.TH "ess_context" 3 "Sun Feb 3 2019" "Version 0.3" "OpenESS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ess_context \- ess context  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ess_context\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBess_backend_facktory_t\fP * \fBbackend\fP"
.br
.ti -1c
.RI "\fBess_format_t\fP \fBformat\fP"
.br
.ti -1c
.RI "\fBess_context_status_t\fP \fBstatus\fP"
.br
.ti -1c
.RI "\fBess_context_error_t\fP \fBlast_error\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ess context 

Embedded sound server context\&. Abstract managment 
.SH "Field Documentation"
.PP 
.SS "\fBess_backend_facktory_t\fP* ess_context::backend"
using backend 
.SS "\fBess_format_t\fP ess_context::format"
backend format 
.SS "\fBess_context_error_t\fP ess_context::last_error"
the last error 
.SS "\fBess_context_status_t\fP ess_context::status"
context status 

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenESS from the source code\&.
