.TH "ess_server" 3 "Sun Feb 3 2019" "Version 0.3" "OpenESS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ess_server
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBhostname\fP"
.br
.ti -1c
.RI "ess_backend_t * \fBbackend\fP"
.br
.ti -1c
.RI "\fBess_format_t\fP \fBformat\fP"
.br
.ti -1c
.RI "int \fBport\fP"
.br
.ti -1c
.RI "int \fBsocket\fP"
.br
.ti -1c
.RI "void * \fBbuffer\fP"
.br
.ti -1c
.RI "int \fBmagl\fP"
.br
.ti -1c
.RI "int \fBmagr\fP"
.br
.ti -1c
.RI "int \fBspeed\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBoffset\fP"
.br
.ti -1c
.RI "\fBess_server_status_t\fP \fBstatus\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "ess_backend_t* ess_server::backend"

.SS "void* ess_server::buffer"

.SS "\fBess_format_t\fP ess_server::format"

.SS "const char* ess_server::hostname"

.SS "int ess_server::length"

.SS "int ess_server::magl"

.SS "int ess_server::magr"

.SS "int ess_server::offset"

.SS "int ess_server::port"

.SS "int ess_server::socket"

.SS "int ess_server::speed"

.SS "\fBess_server_status_t\fP ess_server::status"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenESS from the source code\&.
