.TH "ess_backends_entry" 3 "Sun Feb 3 2019" "Version 0.3" "OpenESS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ess_backends_entry
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const char * \fBname\fP"
.br
.ti -1c
.RI "\fBess_backend_facktory_t\fP *(* \fBgetFactory\fP )(void)"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "\fBess_backend_facktory_t\fP*(*  ess_backends_entry::getFactory) (void)"

.SS "const char* ess_backends_entry::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for OpenESS from the source code\&.
