.TH "lib/esd/format.c" 3 "Sat Feb 2 2019" "Version 0.3" "OpenESS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/esd/format.c \- ESS format source\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'format\&.h'\fP
.br
\fC#include <stdio\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBess_format_get_channels\fP (\fBess_format_t\fP format)"
.br
.RI "Help to get the number of channels of the format\&. "
.ti -1c
.RI "int \fBess_format_get_samplerate\fP (\fBess_format_t\fP format)"
.br
.RI "Help to get the samplerate of the format\&. "
.ti -1c
.RI "int \fBess_format_get_bits\fP (\fBess_format_t\fP format)"
.br
.RI "Help to get bits of the format\&. "
.ti -1c
.RI "const char * \fBess_format_to_string\fP (\fBess_format_t\fP format)"
.br
.RI "Help to get the string of the format\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "char \fB__g_format_buffer\fP [32]"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESS format source\&. 


.PP
\fBAuthor:\fP
.RS 4
Anna Sopdia Schröck 
.RE
.PP
\fBDate:\fP
.RS 4
30 Januar 20119 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "int ess_format_get_bits (\fBess_format_t\fP format)"

.PP
Help to get bits of the format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIformat\fP The format to parse 
.RE
.PP

.SS "int ess_format_get_channels (\fBess_format_t\fP format)"

.PP
Help to get the number of channels of the format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIformat\fP The format to parse 
.RE
.PP

.SS "int ess_format_get_samplerate (\fBess_format_t\fP format)"

.PP
Help to get the samplerate of the format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIformat\fP The format to parse 
.RE
.PP

.SS "const char* ess_format_to_string (\fBess_format_t\fP format)"

.PP
Help to get the string of the format\&. 
.PP
\fBParameters:\fP
.RS 4
\fIformat\fP The format to parse 
.RE
.PP

.SH "Variable Documentation"
.PP 
.SS "char __g_format_buffer[32]"

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenESS from the source code\&.
