.TH "lib/esd/backend/i2s_gerneric_backend.c" 3 "Sun Feb 3 2019" "Version 0.3" "OpenESS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/esd/backend/i2s_gerneric_backend.c
.SH SYNOPSIS
.br
.PP
\fC#include 'ess_format\&.h'\fP
.br
\fC#include 'config\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for OpenESS from the source code\&.
