.TH "lib/esd/backend/udp_backend.h" 3 "Sun Feb 3 2019" "Version 0.3" "OpenESS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
lib/esd/backend/udp_backend.h \- ESS udp backend - send audio over udp4 oder udp6\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBess_backend_facktory_t\fP * \fBess_backend_udp_getFactory\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
ESS udp backend - send audio over udp4 oder udp6\&. 


.PP
\fBAuthor:\fP
.RS 4
Anna Sopdia Schröck 
.RE
.PP
\fBDate:\fP
.RS 4
30 Januar 20119 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "\fBess_backend_facktory_t\fP* ess_backend_udp_getFactory ()"
get the udp_backend factory 
.SH "Author"
.PP 
Generated automatically by Doxygen for OpenESS from the source code\&.
